### ISSUE TITLE
Make this repository archive

### ISSUE THREAD

**Issue by Happy2018new** [rnhws-Team/ToolDelta-PhoenixBuilder#1]
It's seems that `Neomega` provide better features and functions that could replace the older one which have been removed in [LNSSPsd/PhoenixBuilder](https://github.com/LNSSPsd/PhoenixBuilder).
So, maybe it's time for us to archive this repository when everything prepare down.

**Comment by SuperScript-PRC** [comment]
Means it's gonna closed...?

**Comment by RainyHallways** [comment]
Approve

**Comment by Happy2018new** [comment]
> Means it's gonna closed...?

I'm not sure about that, and I think you are the ultimate decision maker in this matter.

**Comment by RainyHallways** [comment]
Nope,In case we probably need to make any changes in the future, we can always refer to the code in this repo. However, we will not be actively updating in this codebase. If you have any questions or concerns about this decision, please let me know.



---- Replied Message ----
| From | Eternal ***@***.***> |
| Date | 01/06/2024 19:37 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [rnhws-Team/ToolDelta-PhoenixBuilder] Make this repository archive (Issue #1) |

Means it's gonna closed...?

I'm not sure about that, and I think you are the ultimate decision maker in this matter.

**Comment by SuperScript-PRC** [comment]
okay, make it closed then since the project will be moved to another repository(Probably mine).



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月6日(星期六) 晚上7:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rnhws-Team/ToolDelta-PhoenixBuilder] Make this repository archive (Issue #1)





 Nope,In case we probably need to make any changes in the future, we can always refer to the code in this repo. However, we will not be actively updating in this codebase. If you have any questions or concerns about this decision, please let me know.
 
 
 
 ---- Replied Message ----
 | From | Eternal ***@***.***&gt; |
 | Date | 01/06/2024 19:37 |
 | To | ***@***.***&gt; |
 | Cc | ***@***.***&gt;***@***.***&gt; |
 | Subject | Re: [rnhws-Team/ToolDelta-PhoenixBuilder] Make this repository archive (Issue #1) |
 
 Means it's gonna closed...?
 
 I'm not sure about that, and I think you are the ultimate decision maker in this matter.

**Comment by Happy2018new** [comment]
Which project will move? This repo or SuperScript/ToolDelta?

**Comment by Happy2018new** [comment]
> Which project will move? This repo or SuperScript/ToolDelta?

**Comment by RainyHallways** [comment]
Close as not planned

**Comment by SuperScript-PRC** [comment]
> Which project will move? This repo or SuperScript/ToolDelta?

this repo, since it's a bit of useful for ~/ToolDelta(because of NeOmega's not enough supports  nowadays)

**Comment by Happy2018new** [comment]
> this repo, since it's a bit of useful for ~/ToolDelta(because of NeOmega's not enough supports nowadays)

oh，把这个存储库移走并不是一个绝佳的选择（我未来可能还需要依赖它），所以别移走吧？
